# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=10000)),
                ('file', models.FileField(upload_to='/static/sent_docs')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
