# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='trans_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_from', to='ru.Language'),
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='trans_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.Language'),
        ),
        migrations.AlterField(
            model_name='sentdoc',
            name='file',
            field=models.FileField(upload_to='D:\\projects\\trans/static/sent_docs'),
        ),
    ]
