# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0003_auto_20161229_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='D:\\projects\\trans/static/sent_docs')),
            ],
        ),
        migrations.RemoveField(
            model_name='sentdoc',
            name='file',
        ),
        migrations.AddField(
            model_name='sentfiles',
            name='sent_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ru.SentDoc'),
        ),
    ]
