# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-31 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='role_name',
        ),
    ]
