# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0008_auto_20161231_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.OrderStatus'),
        ),
    ]
