# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ru', '0010_auto_20170102_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sentdoc',
            name='resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to=settings.AUTH_USER_MODEL),
        ),
    ]
