# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0011_auto_20170102_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='files_qnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='text_qnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
