# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-01 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0012_auto_20170102_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='status_name',
            new_name='name',
        ),
    ]
