# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0013_auto_20170102_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='order_src',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ru.OrderSource'),
        ),
    ]
