# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0014_auto_20170102_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentfiles',
            name='file_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
