# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0018_paymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='paymethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.PayMethod'),
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='paystatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.PayStatus'),
        ),
    ]
