# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 23:26
from __future__ import unicode_literals

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0019_auto_20170105_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
