# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 23:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0020_orderstatus_position'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderstatus',
            managers=[
                ('pos_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
