# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0022_auto_20170105_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelManagers(
            name='orderstatus',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='position_n',
            new_name='position',
        ),
    ]
