# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0023_auto_20170105_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Translator_Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.Language')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.Translator')),
            ],
        ),
    ]
