# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ru', '0024_translator_translator_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='data_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='translator_lang',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
