# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0025_auto_20170105_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translator',
            old_name='data_birth',
            new_name='date_birth',
        ),
    ]
