# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0026_auto_20170105_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translator',
            old_name='mail',
            new_name='email',
        ),
    ]
