# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0027_auto_20170105_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='translator_lang',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='translator_lang',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
