# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0028_auto_20170106_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator_lang',
            name='changed',
        ),
        migrations.RemoveField(
            model_name='translator_lang',
            name='registered',
        ),
        migrations.AddField(
            model_name='translator',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='translator',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
