# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0030_translator_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator_lang',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
