# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0033_translator_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\trans/static/photo'),
        ),
    ]
