# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0035_auto_20170108_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translator',
            name='date_birth',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
