# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-08 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0036_auto_20170108_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentdoc',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='ru.Translator'),
        ),
    ]
