# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0037_auto_20170109_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='D:\\projects\\trans/static/translation_files')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.SentDoc')),
            ],
        ),
    ]
