# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0038_translationfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='payment_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
