# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0039_sentdoc_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationfiles',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
