# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0041_translator_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='translator',
            name='init_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
