# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0044_sentdoc_calc_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
