# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0046_sentdoc_translation_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='translation_files',
            field=models.BooleanField(default=False),
        ),
    ]
