# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ru', '0047_sentdoc_translation_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
