# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0048_sentdoc_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentdoc',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
