# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-12 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0052_translator_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='author',
        ),
    ]
