# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0054_ordercomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomments',
            name='athor_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ru.Role'),
        ),
    ]
