# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0055_ordercomments_athor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercomments',
            old_name='athor_role',
            new_name='author_role',
        ),
    ]
