# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-13 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0065_sentdoc_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdoc',
            name='paid_to_manager',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='paid_to_manager_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='paid_to_translator',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentdoc',
            name='paid_to_translator_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sentdoc',
            name='comments',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sentdoc',
            name='translation_files',
            field=models.NullBooleanField(default=False),
        ),
    ]
