# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0067_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='orders_complete',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='orders_in_progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='orders_paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
