# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-22 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ru', '0075_ordercommentsclients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercommentsclients',
            old_name='author_role',
            new_name='answer_author_role',
        ),
        migrations.RemoveField(
            model_name='ordercommentsclients',
            name='author',
        ),
        migrations.AddField(
            model_name='ordercommentsclients',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordercommentsclients',
            name='answer_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
