# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0079_backcallcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='backcall',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
