# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-23 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0080_backcall_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backcallcomments',
            old_name='order',
            new_name='back_call',
        ),
    ]
