# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ru', '0082_backcall_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\trans/media/photo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\trans/media/photo'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\trans/media/photo'),
        ),
        migrations.AlterField(
            model_name='sentfiles',
            name='file',
            field=models.FileField(upload_to='D:\\projects\\trans/media/sent_docs'),
        ),
        migrations.AlterField(
            model_name='translationfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='D:\\projects\\trans/media/translation_files'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='D:\\projects\\trans/media/photo'),
        ),
    ]
